### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Mati278** [carrotdevs/geode-clicksound#29]
entering to your profile with the mod enabled crashes the game for no reason

https://github.com/carrotdevs/geode-clicksound/assets/100154995/59935078-ed77-4201-a1f3-2c097c0f20df

**Comment by BeatACVR** [comment]
does it still happen when you disable click sounds?

what platform are you on?

**Comment by Mati278** [comment]
> does it still happen when you disable click sounds?
> 
> what platform are you on?

windows

https://github.com/carrotdevs/geode-clicksound/assets/100154995/21c02e81-2b52-4204-a1ef-17a8a187c3cc



doesn't happen when disabled

**Comment by BeatACVR** [comment]
send the crashlog

**Comment by Mati278** [comment]
2024-03-10T21:40:54-0500
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v2.0.0-beta.22
Loader Commit: d90bfdd
Bindings Commit: 179edb2
Installed mods: 23
Problems: 0

== Exception Information ==
Faulty Module: E:\Geometry Dash v2.204\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 003A5911 (GeometryDash.exe + 25911)
Number Parameters: 2

== Stack Trace ==
 - E:\Geometry Dash v2.204\GeometryDash.exe + 25911
 - E:\Geometry Dash v2.204\GeometryDash.exe + 258ac
 - 04CA0582
 - E:\Geometry Dash v2.204\geode\unzipped\beat.click-sound\beat.click-sound.dll + 23a1a
 - E:\Geometry Dash v2.204\geode\unzipped\beat.click-sound\beat.click-sound.dll + 7043
 - E:\Geometry Dash v2.204\GeometryDash.exe + 27c6d0
 - E:\Geometry Dash v2.204\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)
 - E:\Geometry Dash v2.204\libcocos2d.dll + f8df9 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
 - E:\Geometry Dash v2.204\libcocos2d.dll + be92c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
 - E:\Geometry Dash v2.204\libcocos2d.dll + c7922 (cocos2d::CCEGLView::onGLFWMouseCallBack + 210)
 - E:\Geometry Dash v2.204\libcocos2d.dll + c794e (cocos2d::CCEGLView::onGLFWMouseCallBack + 254)
 - E:\Geometry Dash v2.204\libcocos2d.dll + 116cc9 (cocos2d::CCPoint::unrotate + 8073)
 - E:\Geometry Dash v2.204\libcocos2d.dll + 118819 (cocos2d::CCPoint::unrotate + 15065)
 - C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\Windows\System32\USER32.dll + 372f6 (GetSystemMetricsForDpi + 3142)
 - C:\Windows\System32\USER32.dll + 35aeb (CallWindowProcW + 27)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
 - C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
 - C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
 - C:\Windows\System32\USER32.dll + 36471 (DispatchMessageW + 1265)
 - C:\Windows\System32\USER32.dll + 35f90 (DispatchMessageW + 16)
 - C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 83360 (OverlayHookD3D3 + 121856)
 - E:\Geometry Dash v2.204\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
 - E:\Geometry Dash v2.204\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
 - E:\Geometry Dash v2.204\GeometryDash.exe + 3c12d8
 - E:\Geometry Dash v2.204\Geode.dll + 16f8c4 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
 - E:\Geometry Dash v2.204\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c5e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c2e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 00777f01
EBX: 10b476e0
ECX: 010feed4
EDX: 00000000
EBP: 010feee4
ESP: 010feec0
EDI: 00000000
ESI: 10b476e0
EIP: 003a5911

== Installed Mods ==
  | [v1.0.0] alphalaneous_raydeeux.changefont19
x | [v1.7.1] beat.click-sound
  | [v1.0.1] colon.gold_user_coins
  | [v4.1.3] cvolton.betterinfo
  | [v1.1.0] cvolton.misc_bugfixes
  | [v1.3.2] dankmeme.globed2
  | [v1.5.0] firee.PrismMenu
  | [v2.5.2] fleym.nongd
  | [v1.5.2] geode.custom-keybinds
x | [v2.0.0-beta.22] geode.loader
x | [v1.8.0] geode.node-ids
  | [v6.3.3] hjfod.betteredit
  | [v1.0.0] izzy.practice_sync
  | [v1.0.1] mat.draw-divide
  | [v2.1.0] prevter.openhack
  | [v1.1.3] shineua.geometrize2gd
  | [v1.0.5] sofabeddd.colored_icon_kit
  | [v1.0.1] techstudent10.hide_locks
  | [v1.0.1] thesillydoggo.animatedprofiles
  | [v1.0.0-beta.5] thesillydoggo.comment_emojis
  | [v1.6.9] thesillydoggo.entersearch
  | [v1.6.6] tpdea.betterpause-Better
  | [v1.5.3] zilko.xdbot

**Comment by BeatACVR** [comment]
i cant replicate it. can you disable all mods besides geode, node ids, and click sounds, then try again?

**Comment by Mati278** [comment]
> i cant replicate it. can you disable all mods besides geode, node ids, and click sounds, then try again?


https://github.com/carrotdevs/geode-clicksound/assets/100154995/9e6d05df-cb2f-4269-a3b0-e4d9652056ba

**Comment by Mati278** [comment]
> 2024-03-10T21:40:54-0500 Whoopsies! An unhandled exception has occurred.
> 
> == Geode Information == Loader Version: v2.0.0-beta.22 Loader Commit: d90bfdd Bindings Commit: 179edb2 Installed mods: 23 Problems: 0
> 
> == Exception Information == Faulty Module: E:\Geometry Dash v2.204\GeometryDash.exe Faulty Mod: Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION) Exception Flags: 0 Exception Address: 003A5911 (GeometryDash.exe + 25911) Number Parameters: 2
> 
> == Stack Trace ==
> 
> * E:\Geometry Dash v2.204\GeometryDash.exe + 25911
> * E:\Geometry Dash v2.204\GeometryDash.exe + 258ac
> * 04CA0582
> * E:\Geometry Dash v2.204\geode\unzipped\beat.click-sound\beat.click-sound.dll + 23a1a
> * E:\Geometry Dash v2.204\geode\unzipped\beat.click-sound\beat.click-sound.dll + 7043
> * E:\Geometry Dash v2.204\GeometryDash.exe + 27c6d0
> * E:\Geometry Dash v2.204\libcocos2d.dll + ad27d (cocos2d::CCMenu::ccTouchEnded + 29)
> * E:\Geometry Dash v2.204\libcocos2d.dll + f8df9 (cocos2d::CCTouchDispatcher::touchesEnded + 25)
> * E:\Geometry Dash v2.204\libcocos2d.dll + be92c (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 92)
> * E:\Geometry Dash v2.204\libcocos2d.dll + c7922 (cocos2d::CCEGLView::onGLFWMouseCallBack + 210)
> * E:\Geometry Dash v2.204\libcocos2d.dll + c794e (cocos2d::CCEGLView::onGLFWMouseCallBack + 254)
> * E:\Geometry Dash v2.204\libcocos2d.dll + 116cc9 (cocos2d::CCPoint::unrotate + 8073)
> * E:\Geometry Dash v2.204\libcocos2d.dll + 118819 (cocos2d::CCPoint::unrotate + 15065)
> * C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
> * C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
> * C:\Windows\System32\USER32.dll + 372f6 (GetSystemMetricsForDpi + 3142)
> * C:\Windows\System32\USER32.dll + 35aeb (CallWindowProcW + 27)
> * C:\Windows\SYSTEM32\OPENGL32.dll + 4696f (glDebugEntry + 3631)
> * C:\Windows\System32\USER32.dll + 4139b (AddClipboardFormatListener + 75)
> * C:\Windows\System32\USER32.dll + 37b3a (GetClassLongW + 1962)
> * C:\Windows\System32\USER32.dll + 36471 (DispatchMessageW + 1265)
> * C:\Windows\System32\USER32.dll + 35f90 (DispatchMessageW + 16)
> * C:\Program Files (x86)\Steam\gameoverlayrenderer.dll + 83360 (OverlayHookD3D3 + 121856)
> * E:\Geometry Dash v2.204\libcocos2d.dll + 117472 (cocos2d::CCPoint::unrotate + 10034)
> * E:\Geometry Dash v2.204\libcocos2d.dll + c4dd0 (cocos2d::CCApplication::run + 720)
> * E:\Geometry Dash v2.204\GeometryDash.exe + 3c12d8
> * E:\Geometry Dash v2.204\Geode.dll + 16f8c4 (gdMainHook + 532 | D:\a\geode\geode\loader\src\platform\windows\main.cpp:59)
> * E:\Geometry Dash v2.204\GeometryDash.exe + 3c267e
> * C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
> * C:\Windows\SYSTEM32\ntdll.dll + 67c5e (RtlGetAppContainerNamedObjectPath + 286)
> * C:\Windows\SYSTEM32\ntdll.dll + 67c2e (RtlGetAppContainerNamedObjectPath + 238)
> 
> == Register States == EAX: 00777f01 EBX: 10b476e0 ECX: 010feed4 EDX: 00000000 EBP: 010feee4 ESP: 010feec0 EDI: 00000000 ESI: 10b476e0 EIP: 003a5911
> 
> == Installed Mods == | [v1.0.0] alphalaneous_raydeeux.changefont19 x | [v1.7.1] beat.click-sound | [v1.0.1] colon.gold_user_coins | [v4.1.3] cvolton.betterinfo | [v1.1.0] cvolton.misc_bugfixes | [v1.3.2] dankmeme.globed2 | [v1.5.0] firee.PrismMenu | [v2.5.2] fleym.nongd | [v1.5.2] geode.custom-keybinds x | [v2.0.0-beta.22] geode.loader x | [v1.8.0] geode.node-ids | [v6.3.3] hjfod.betteredit | [v1.0.0] izzy.practice_sync | [v1.0.1] mat.draw-divide | [v2.1.0] prevter.openhack | [v1.1.3] shineua.geometrize2gd | [v1.0.5] sofabeddd.colored_icon_kit | [v1.0.1] techstudent10.hide_locks | [v1.0.1] thesillydoggo.animatedprofiles | [v1.0.0-beta.5] thesillydoggo.comment_emojis | [v1.6.9] thesillydoggo.entersearch | [v1.6.6] tpdea.betterpause-Better | [v1.5.3] zilko.xdbot

> > i cant replicate it. can you disable all mods besides geode, node ids, and click sounds, then try again?
> 
>  Geometry.Dash.2024-03-10.21-40-48.mp4

crashlog for that one

**Comment by MuhXd** [comment]
is it only your profile

**Comment by Mati278** [comment]
nvm
